--liquibase formatted sql

--changeset akorobov:1
CREATE TABLE IF NOT EXISTS card_request
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id    BIGINT REFERENCES card (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(64) NOT NULL,
    status     VARCHAR(64) NOT NULL,
    created_at TIMESTAMP   NOT NULL
);


