--liquibase formatted sql

--changeset akorobov:1
CREATE TABLE IF NOT EXISTS outbox_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       UUID        NOT NULL UNIQUE,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id   BIGINT      NOT NULL,
    event_type      VARCHAR(64) NOT NULL,
    payload        JSONB       NOT NULL,
    event_status         VARCHAR(64) NOT NULL DEFAULT 'NEW',
    created_at     TIMESTAMP   NOT NULL,
    published_at   TIMESTAMP,
    retry_count    INTEGER     DEFAULT 0,
    last_error     TEXT
);


