#
# application.yml — главный конфигурационный файл Spring Boot.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards
    username: postgres
    password: korobov
    driver-class-name: org.postgresql.Driver
