CREATE  TABLE card (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    card_number varchar(255) NOT NULL,
    balance NUMERIC(19,2) NOT NULL,
    expire_date DATE,
    status VARCHAR(50) not null,
    user_id BIGINT NOT NULL
)