--liquibase formatted sql

--changeset akorobov:1
CREATE TABLE IF NOT EXISTS refresh_token
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token   VARCHAR NOT NULL,
    user_id BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expiry_date TIMESTAMP NOT NULL
);


