--liquibase formatted sql

--changeset akorobov:1
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname  VARCHAR(64)  NOT NULL,
    lastname   VARCHAR(64)  NOT NULL,
    birth_date DATE  NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL ,
    password   VARCHAR  NOT NULL,
    role       VARCHAR(64)  NOT NULL
);

--changeset akorobov:2
CREATE TABLE IF NOT EXISTS card
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL,
    card_number varchar(255)   NOT NULL,
    expire_date DATE,
    status      VARCHAR(50)    NOT NULL,
    balance     NUMERIC(19, 2) NOT NULL

)
