spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/bank_cards}
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: korobov
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: 6379

logging:
  file:
    name: ./logs/application.log

  level:
    root: INFO
    com.example: DEBUG


jwt:
  secret: "SamsungSamsungSamsungSamsungSamsung"
  expiration:
    access: 900000
    refresh: 604800000

outbox:
  batchSize: 100

app:
  kafka:
    topics:
      bankEvents: bank-events