DELETE FROM card;
DELETE FROM refresh_token;
DELETE FROM users;
DELETE FROM outbox_event;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE card ALTER COLUMN id RESTART WITH 1;
ALTER TABLE refresh_token ALTER COLUMN id RESTART WITH 1;
ALTER TABLE outbox_event ALTER COLUMN id RESTART WITH 1;
