DELETE FROM card;
DELETE FROM refresh_token;
DELETE FROM users;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE card ALTER COLUMN id RESTART WITH 1;
ALTER TABLE refresh_token ALTER COLUMN id RESTART WITH 1;
